# Generated by Django 3.2.11 on 2022-02-01 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='stock_symbol',
            new_name='symbol',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='stock_symbol',
            new_name='symbol',
        ),
        migrations.RemoveField(
            model_name='history',
            name='stock_name',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='stock_name',
        ),
    ]
